
import { Button, Radio, Checkbox, Row, Col } from 'antd'
import styles from '../styles/instruction.module.css'
import React, { useState } from 'react';
import Image from 'next/image'




export default function Explanation({ partOrder, partInd, readExplanation, setReadExplanation }) {

    const continueChange = () => {
        setReadExplanation(true);

    }


    return (
        <>
            {(partOrder[partInd] == 3) ?
                <>
                    <div className={styles.container}>
                        <p>This visualization paradigm is generated with the projected boundary points of the 2D/3D registration result of the pelvis. Please take a look at the following images and answer the questions below. </p>
                        <div className={styles.imageBox}>
                            <Image className={styles.imageBorder} src={'/contour1.png'} height={350} width={650}></Image>
                        </div>
                        <div className={styles.imageBox}>
                            <Image className={styles.imageBorder} src={'/contour2.png'} height={350} width={650}></Image>
                        </div>

                        <div className={styles.buttonContainer}>
                            <Button variant="btn btn-success" onClick={continueChange}>Continue</Button>
                        </div>
                    </div>
                </>
                : (partOrder[partInd] == 1) ?
                    <>
                        <div className={styles.container}>
                            <p>This visualization paradigm is generated by searching through the local regions of the digitally reconstructed radiograph to find the best match in the original x-ray and visualizing the vectors as arrows.</p>
                            <div className={styles.imageBox}>
                                <Image className={styles.imageBorder} src={'/arrow1.png'} height={350} width={650}></Image>
                            </div>
                            <div className={styles.imageBox}>
                                <Image className={styles.imageBorder} src={'/arrow2.png'} height={350} width={650}></Image>
                            </div>
                            <div className={styles.buttonContainer}>
                                <Button variant="btn btn-success" onClick={continueChange}>Continue</Button>
                            </div>
                        </div>
                    </>
                    :
                    <>
                        <div className={styles.container}>

                            <p>This visualization paradigm is generated with the segmentation and boundary points of the 2D/3D registration result of the pelvis as well as the expected segmentation and boundary points of the pelvis from the original x-ray (i.e., visualizes the overlapped regions as well as the misaligned regions). </p>
                            <div className={styles.imageBox}>
                                <Image className={styles.imageBorder} src={'/overlap1.png'} height={350} width={650}></Image>
                            </div>
                            <div className={styles.imageBox}>
                                <Image className={styles.imageBorder} src={'/overlap2.png'} height={350} width={650}></Image>
                            </div>
                            <div className={styles.buttonContainer}>
                                <Button variant="btn btn-success" onClick={continueChange}>Continue</Button>
                            </div>
                        </div>
                    </>


            }



        </>
    )




}