import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { Button } from 'antd'
import 'antd/dist/antd.css'
import React, { Component, useState } from "react"
// import {
//   collection,
//   query,
//   onSnapshot,
//   doc,
//   updateDoc,
//   deleteDoc,
// } from "firebase/firestore";
// import {db} from '../firebase'


export default function Home() {


  const [agree, setAgree] = useState(false);

  const checkboxHandler = () => {
    // if agree === true, it will be set to false
    // if agree === false, it will be set to true
    setAgree(!agree);
    // Don't miss the exclamation mark
}

  return (
    <div className={styles.container}>

      <Head>
        <title>Registration Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to 2D/3D Registration Assessment!
        </h1>
        <p>
          You are being asked to participate in an online study for a research project at Johns Hopkins University. Participation in this study is voluntary and you will receive compensation if you complete the study. Even if you decide to join now, you can change your mind later. If you want to stop your participation in the study, you can simply close the browser. The records and data from the study will only be reviewed by team members involved in the project. We will not ask for information that identifies you, thus, your responses cannot be associated with your identity. This study has been approved by the Homewood IRB. You can read a more detailed informed consent in the following <a href="put_link_to_conset_form" target="_blank">link</a>. By clicking "Continue", you accept these conditions and agree to participate in the study.
        </p>

        <div>
           <input type="checkbox" id="agree" onChange={checkboxHandler} />
            <label htmlFor="agree"> I agree to the <b>terms and conditions</b></label>
        </div>

      <Link
      href= "/instruction" passHref>
        <Button disabled={!agree} component="a">
          Continue
        </Button>
      </Link>

      </main>

      
    </div>
  )
}
